### ISSUE TITLE
Dropdown does not appear to be properly exported

### ISSUE THREAD

**Issue by grahhnt** [mondaycom/monday-ui-react-core#1243]
My project is using TypeScript and doesn't appear to be exported fully

It is possible to import Dropdown from `monday-ui-react-core/dist/Dropdown` instead of the base `monday-ui-react-core` but it does create TS errors due to it not being in index.d.ts

![image](https://user-images.githubusercontent.com/46821216/235518726-066e2eb5-c61a-4296-ab89-de85ee3c2211.png)

**Comment by shlomitc** [comment]
Hey 🙋‍♂️
Thanks for reporting.
The reason is that some components did not finish the migration to typescript just yet, so they didn't have types exposed.
We're working on a fix and will update you when resolved.

**Comment by shlomitc** [comment]
Fix was introduced in version `1.123.0`.

**Comment by marcelfrank-dev** [comment]
Hey @shlomitc,
the fix is hideous and not really helpful. Yes, it fixes the problem of the import, but it's exactly the same if we use ts-ignore. So I can use it, but I do not get any suggestion of props that are available in the component from TypeScript.
![image](https://github.com/mondaycom/monday-ui-react-core/assets/122784386/903f9aa0-dfa9-4998-8965-99c568495169)


If I see it correctly, the Dropdown type exists, it's just not used in the fix.

I think this would make it right:
![image](https://github.com/mondaycom/monday-ui-react-core/assets/122784386/c3c00e74-dfee-40e0-9a9f-db376d59795d)

**Comment by shlomitc** [comment]
Since this component is still in js - these types are a “good guess”. Also -  all props are non-optional so that would make the component api frustrating.

would you like to try and contribute a fix?
Either by making these props optional, or preferably migrate to typescript and then we could easily expose it
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md
