### ISSUE TITLE
[Type]: change "icon" prop type to SubIcon in ModalHeader and Tab

### ISSUE THREAD

**Issue by talkor** [mondaycom/monday-ui-react-core#2025]
In `ModalHeader` and `Tab` components the `icon` prop type should be `SubIcon` instead of `string | React.FunctionComponent<IconSubComponentProps> | null;` (which is the same type) to support TS strict mode better.

**Comment by MohammedHaris96** [comment]
Hey! @talkor I would like to contribute to it.

**Comment by YossiSaadi** [comment]
Hey @MohammedHaris96 !
Thanks for the contribution!
We're sorry that our intention was a bit misunderstood
We want to change the **type** itself, instead of being `string | React.FunctionComponent<IconSubComponentProps> | null;`:
![image](https://github.com/mondaycom/monday-ui-react-core/assets/30905362/7ada6b56-dbb4-4760-ab28-6fd5d4973fd0)
to be:
`SubIcon` from our `types` file:
![image](https://github.com/mondaycom/monday-ui-react-core/assets/30905362/2c008fe7-773a-42c4-a358-08a48d8d87d3)

Our intention was not to change the prop name, but the prop type.
Would you like to give it a shot with a new PR? 😃

**Comment by MohammedHaris96** [comment]
Hey! @YossiSaadi,
Thanks for the confirmation and for making it more clear.
I gave it a shot with a new PR.
Please have a look.
Thanks!😃
